import QuoteForm from '@/components/quote/QuoteForm'
import Script from 'next/script'
import Link from 'next/link'
import FAQ from '@/components/FAQ';

export const metadata = {
    title: 'Car Shipping Cost Calculator (2026) | Instant Quote',
    description: 'Calculate car shipping rates instantly with our transparent cost estimator. Get real-time 2026 quotes for open & enclosed transport. No deposit required.',
    keywords: 'auto transport quote, car shipping calculator, vehicle transport cost, auto shipping estimate',
    openGraph: {
        title: 'Car Shipping Cost Calculator (2026) | Instant Quote',
        description: 'Get instant quotes for professional car shipping services across the USA.',
    },
    alternates: {
        canonical: '/car-shipping-cost-calculator',
    },
}

export default function GetQuotePage() {
    const faqs = [
        {
            question: "Does the calculator include insurance?",
            answer: "Yes. Every quote generated by Furious Auto Shipping includes comprehensive bumper-to-bumper cargo insurance. Your vehicle is fully covered during transit against damage caused by carrier negligence or equipment failure"
        },
        {
            question: "Why is my final quote different than the calculator estimate?",
            answer: "Our calculator provides a highly accurate estimate based on historical data. However, if you are shipping on a route with extremely low driver availability (a \"dead zone\") or during a fuel spike, the final dispatch price may vary slightly to secure a driver. We will always communicate this transparently."
        },
        {
            question: "Is there an upfront deposit?",
            answer: "No. Furious Auto Shipping operates on a performance basis. We do not charge a deposit until we have successfully assigned a carrier to pick up your vehicle. You can get a quote and book your order with $0 down."
        },
    ]
    return (
        <>
            <Script
                id="calculator-schema"
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify({
                        "@context": "https://schema.org",
                        "@graph": [
                            {
                                "@type": "SoftwareApplication",
                                "name": "Furious Auto Shipping Cost Calculator",
                                "operatingSystem": "All",
                                "applicationCategory": "BusinessApplication",
                                "url": "https://furiousautoshipping.com/car-shipping-cost-calculator",
                                "description": "Instant auto transport cost estimator. Calculate shipping rates for open and enclosed transport based on real-time 2026 fuel indexes and route data.",
                                "offers": {
                                    "@type": "Offer",
                                    "price": "0",
                                    "priceCurrency": "USD",
                                    "availability": "https://schema.org/InStock"
                                },
                                "aggregateRating": {
                                    "@type": "AggregateRating",
                                    "ratingValue": "4.8",
                                    "ratingCount": "156",
                                    "bestRating": "5",
                                    "worstRating": "1"
                                },
                                "author": {
                                    "@type": "Organization",
                                    "name": "Furious Auto Shipping",
                                    "url": "https://furiousautoshipping.com"
                                }
                            },
                            {
                                "@type": "BreadcrumbList",
                                "itemListElement": [
                                    {
                                        "@type": "ListItem",
                                        "position": 1,
                                        "name": "Home",
                                        "item": "https://furiousautoshipping.com"
                                    },
                                    {
                                        "@type": "ListItem",
                                        "position": 2,
                                        "name": "Car Shipping Cost Calculator",
                                        "item": "https://furiousautoshipping.com/car-shipping-cost-calculator"
                                    }
                                ]
                            }
                        ]
                    })
                }}
            />
            <div className="min-h-screen bg-gray-50 pt-20">
                <div className="container py-12">
                    <div className="max-w-4xl mx-auto">
                        {/* Header */}
                        <div className="text-center mb-12">
                            <h1 className="heading-2 text-gray-900 mb-4">
                                How Our Car Shipping Cost Calculator Works
                            </h1>
                        </div>

                        {/* Quote Form */}
                        <QuoteForm />
                    </div>
                </div>
            </div>

            <section className="section">
                <div className="container">
                    <p className='my-2'>You’ve seen the quote form above—now, let's unpack the numbers. Unlike generic estimators that rely on static, outdated pricing tables, the <Link className='font-bold text-brand-500' href='/'>Furious Auto Shipping</Link> calculator utilizes real-time market data. Our algorithm integrates current <b>national fuel indexes</b>, route availability (supply and demand), and carrier capacity to provide a highly accurate <Link className='font-bold text-brand-500' href='/'>vehicle transport quote</Link>.</p>
                    <p className='my-2'>We believe in total transparency. When you calculate car shipping rates with us, you aren't just getting a random guess; you are viewing a price that reflects the current logistics market.</p>

                    <h2 className="heading-2 mb-6">What Determines Your Auto Transport Rate?</h2>
                    <p className='my-2'>To understand "how much to ship a car," you must understand the logistics variables that carriers use to generate a price. Our <Link className='font-bold text-brand-500' href='/'>auto transport cost estimator</Link> weighs five primary factors:</p>

                    <h3 className="text-lg font-bold mb-6">1. Distance (Mileage & Route Logistics)</h3>
                    <p className='my-2'>While it is true that a longer trip costs more in total, the cost per mile actually decreases as the distance increases. Short-haul trips (under 500 miles) have a higher cost per mile due to the time involved in loading and unloading. Cross-country routes allow drivers to cover more ground efficiently, lowering the per-mile rate.</p>

                    <h3 className="text-lg font-bold mb-6">2. Vehicle Size & Weight (displacement)</h3>
                    <p className='my-2'>Carriers have strict weight limits (usually 80,000 lbs total). A Ford F-150 or an SUV takes up more physical space and adds more weight to the trailer than a Honda Civic. Heavies vehicles reduce the total number of cars a hauler can carry, resulting in a higher premium to offset the lost capacity.</p>

                    <h3 className="text-lg font-bold mb-6">3. Transport Type: Open vs. Enclosed</h3>
                    <p className='my-2'><Link className='font-bold text-brand-500' href='/services/open-auto-transport'>Open Transport</Link> is the industry standard and the most cost-effective method. <Link className='font-bold text-brand-500' href='/services/enclosed-auto-transport'>Enclosed Transport</Link> offers protection from road debris and weather but typically comes with a 40-60% price premium. This is because enclosed trailers hold fewer vehicles and require specialized insurance coverage.</p>

                    <h3 className="text-lg font-bold mb-6">4. Vehicle Condition (Inoperable Fee)</h3>
                    <p className='my-2'>If your vehicle cannot start, brake, or steer under its own power, the carrier must use a winch to load it. This labor-intensive process requires a specialized driver and equipment, adding a "winch fee" (typically $150-$200) to your base rate.</p>

                    <h3 className="text-lg font-bold mb-6">5. Seasonality & Market Demand</h3>
                    <p className='my-2'>Auto shipping is a commodity market. Prices fluctuate based on supply and demand.</p>
                    <ul className='list-disc ml-4'>
                        <li className='my-2'><b>Snowbird Season (Jan/Feb):</b> Routes leaving the Northeast for Florida or Arizona see price spikes due to high demand.</li>
                        <li className='my-2'><b>Summer Peak (June/July):</b> High volume moves typically increase rates nationwide.</li>
                    </ul>

                    <h2 className="heading-2 mb-6">Estimated Car Shipping Rates by Distance (2026)</h2>
                    <p className='my-2'>Google and users alike want clarity on pricing. While every shipment is unique, the table below provides a baseline for what you can expect when you use our <Link className='font-bold text-brand-500' href=''>Car Shipping Cost Calculator</Link>.</p>

                    <h2 className="text-2xl font-bold text-gray-900 mb-6">
                        Estimated Car Shipping Rates by Distance (2026)
                    </h2>

                   <div className="overflow-auto">
                     <table className="w-full border-collapse border border-gray-300">
                        <thead>
                            <tr className="bg-gray-100">
                                <th className="border border-gray-300 p-3 text-left">Distance</th>
                                <th className="border border-gray-300 p-3 text-left">Vehicle Type</th>
                                <th className="border border-gray-300 p-3 text-left">Est. Open Price</th>
                                <th className="border border-gray-300 p-3 text-left">Est. Enclosed Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td className="border border-gray-300 p-3">0-500 Miles (Short Haul)</td>
                                <td className="border border-gray-300 p-3">Sedan</td>
                                <td className="border border-gray-300 p-3">$400 - $600</td>
                                <td className="border border-gray-300 p-3">$650 - $900</td>
                            </tr>
                            <tr className="bg-gray-50">
                                <td className="border border-gray-300 p-3">500-1,500 Miles (Medium)</td>
                                <td className="border border-gray-300 p-3">Sedan</td>
                                <td className="border border-gray-300 p-3">$700 - $1,100</td>
                                <td className="border border-gray-300 p-3">$1,000 - $1,500</td>
                            </tr>
                            <tr>
                                <td className="border border-gray-300 p-3">1,500+ Miles (Cross Country)</td>
                                <td className="border border-gray-300 p-3">Sedan</td>
                                <td className="border border-gray-300 p-3">$1,100 - $1,500</td>
                                <td className="border border-gray-300 p-3">$1,600 - $2,100</td>
                            </tr>
                        </tbody>
                    </table>
                   </div>

                    <div className="mt-4 p-4 bg-gray-100 border-l-4 border-gray-400">
                        <p className="text-sm text-gray-700">
                            <strong>Note:</strong> Prices listed above are market estimates based on standard sedan sizes. Actual rates may vary based on daily fuel surcharges and route congestion.
                        </p>
                    </div>

                    <h2 className="heading-2 mb-6">Calculator Breakdown: Open vs. Enclosed Transport</h2>
                    <p className='my-2'>When utilizing our <b>Car Shipping Cost Calculator</b>, you will see options for both carrier types. Here is the financial breakdown to help you decide:</p>
                    <ul className='list-disc ml-4'>

                        <li className='my-2'><b>Open Transport:</b> This is how dealerships ship 95% of new inventory. It is safe, efficient, and cost-effective. <b>Recommendation:</b> Choose Open for daily drivers, standard sedans, and SUVs.</li>
                        <li className='my-2'><b>Enclosed Transport:</b> This method utilizes hard-sided or soft-sided trailers to shield the vehicle completely. <b>Recommendation:</b> We advise selecting Enclosed only if your vehicle is a classic, exotic, or luxury car with a value exceeding <b>$75,000</b>. The extra cost is an investment in peace of mind for high-value assets.</li>
                    </ul>

                    <h2 className="heading-2 mb-6">How to Lower Your Car Shipping Quote</h2>
                    <p className='my-2'>We strive to provide fair market pricing, but there are strategic ways to reduce your costs without sacrificing service quality.</p>
                    <ul className='list-disc ml-4'>
                        <li className='my-2'><b>Book Early (The 2-Week Rule):</b> Last-minute "expedited" dispatching forces us to pay premiums to secure a spot on a truck instantly. Booking at least 2 weeks in advance allows us to negotiate the best rate with our carrier network.</li>
                        <li className='my-2'><b>Be Flexible with Dates:</b> If you require a strict pickup on a specific Tuesday, it limits our carrier options. Offering a 3-5 day pickup window allows us to pair your vehicle with a carrier already driving that route, saving you money.</li>
                        <li className='my-2'><b>Ship Terminal-to-Terminal:</b> Door-to-door is the standard, but it requires the driver to navigate residential streets. If you are near a major hub, ask if a terminal drop-off is available—it saves driver labor and fuel, savings which are passed on to you.</li>
                    </ul>

                </div>
            </section>

            <FAQ
                title="Frequently Asked Questions About Shipping Costs"
                subtitle="Common questions about Florida auto transport services"
                faqs={faqs} />
        </>
    )
}